import Head from 'next/head';
import Image from 'next/image';
import { MdOutlineEmail } from 'react-icons/md';
import { BsTelephone } from 'react-icons/bs';
import Headerlogin from '../../components/Headerlogin';
import Notificationlogin from '../../components/Notificationlogin';
import { signIn } from 'next-auth/react';
import Register from '../../components/register';
import Link from 'next/link';
import { PropagateLoader } from 'react-spinners';
import { useState, useEffect } from 'react';

export default function RegisterSite() {
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
    }, 4000);
  }, []);
  return (
    <div className="w-full min-h-screen h-full bg-[url('/slider/cafe2.jpg')] bg-cover lg:bg-gradient-to-br lg:from-cyan-100 dark:lg:from-gray-600 dark:lg:to-gray-900 dark:md:from-gray-600 dark:md:to-gray-900 lg:to-blue-500 md:bg-gradient-to-br md:from-cyan-100 md:to-blue-500">
      <Head>
        <title>Ilife: Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon_io/favicon.ico" />
      </Head>
      {loading ? (
        <div className="flex justify-center items-center h-screen w-screen bg-card-light dark:bg-card-dark">
          <PropagateLoader
            color={
              window.localStorage.getItem('theme') === 'dark' ? '#fff' : '#000'
            }
          />
        </div>
      ) : (
        <>
          <Headerlogin />
          <main className="lg:pb-20 md:pb-4 pb-4">
            <div className="lg:bg-cover md:mx-10 lg:mx-52 md:bg-[url('/slider/cafe2.jpg')] md:rounded-2xl lg:bg-[url('/slider/cafe2.jpg')] lg:rounded-2xl drop-shadow-xl">
              <section className="md:w-96 relative grid grid-cols-2 bg-white dark:bg-card-dark text-headlines-light dark:text-primary-dark mx-4 md:mx-0 lg:mx-0 px-5 py-8 rounded-2xl lg:min-w-fit drop-shadow-lg">
                <h1 className="col-span-2 text-center text-3xl font-bold mb-8">
                  Sign Up
                </h1>
                <div className="flex col-span-2 justify-evenly items-center mb-8">
                  <div className="group">
                    <Link
                      className="flex items-center gap-3 text-primary-light dark:text-primary-dark"
                      href=""
                    >
                      <MdOutlineEmail className="w-10 h-10 px-2.5 dark:bg-container-dark bg-container-light rounded-3xl group-hover:rounded-xl transition-all ease-linear text-icons" />

                      <span className="text-sm">Email</span>
                    </Link>
                  </div>
                  <div className="group">
                    <Link
                      className="flex items-center gap-3 text-primary-light dark:text-primary-dark  "
                      href=""
                    >
                      <BsTelephone className="w-10 h-10 px-2.5 dark:bg-container-dark bg-container-light rounded-3xl group-hover:rounded-xl transition-all ease-linear text-icons " />

                      <span className="text-sm">Phone Number</span>
                    </Link>
                  </div>
                </div>
                <Register />
                <div className="col-span-2 text-center text-sm">
                  <p className="mb-5">
                    By signing up, I agree to Ilife{' '}
                    <Link className="text-icons" href="/termsofuse">
                      Terms of Use
                    </Link>{' '}
                    and <br></br>
                    <Link className="text-icons" href="/policy">
                      Privacy Policy.
                    </Link>
                  </p>
                  <p className="text-base font-semibold mb-5">
                    or continue with
                  </p>
                </div>
                <div className="flex gap-4 justify-center flex-row mb-10 col-span-2">
                  <button
                    className="flex items-center border-2 shadow-lg px-8 py-4 mb-9 rounded-2xl hover:rounded-md transition-all ease-linear dark:border-container-dark"
                    onClick={() => signIn('google', { callbackUrl: '/' })}
                  >
                    <Image
                      src="/google.svg"
                      width={25}
                      height={25}
                      alt="google"
                    />
                  </button>
                  <button
                    className="flex items-center border-2 shadow-lg px-8 py-4 mb-9 rounded-2xl hover:rounded-md dark:border-container-dark transition-all ease-linear "
                    onClick={() => signIn('facebook', { callbackUrl: '/' })}
                  >
                    <Image
                      src="/facebook.png"
                      width={25}
                      height={25}
                      alt="facebook"
                    />
                  </button>
                  <button
                    className="flex items-center border-2 shadow-lg px-8 py-4 mb-9 rounded-2xl hover:rounded-md transition-all ease-linear dark:border-container-dark "
                    onClick={() => signIn('twitter', { callbackUrl: '/' })}
                  >
                    <Image
                      src="/twitter.png"
                      width={25}
                      height={25}
                      alt="twitter"
                    />
                  </button>
                </div>
                <Notificationlogin />
              </section>
            </div>
          </main>
        </>
      )}
    </div>
  );
}
