import Link from 'next/link';
import Image from 'next/image';
import Head from 'next/head';
import DarkSwitch from '../components/DarkSwitch';
export default function Policy() {
  return (
    <div>
      <Head>
        <title>Ilife: FAQ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon_io/favicon.ico" />
      </Head>

      <nav className="flex justify-between px-4 py-6 md:px-10 lg:px-52 lg:py-6">
        <Link className="dark:hidden w-max" href="/">
          <Image src="/vibrant_logo.svg" width={130} height={130} />
        </Link>
        <Link className="dark:block" href="/">
          <Image src="/logo_white.svg" width={130} height={130} />
        </Link>
        <DarkSwitch />
      </nav>
      <div className="px-4 py-6 md:px-10 lg:px-52 lg:py-6">
        <h1 className="font-bold text-3xl mb-5">FAQ</h1>
        <div className="w-5/6">
          <ol>
            <li className="mb-10">
              <h1 className="text-lg font-semibold mb-4">1. What is Ilife?</h1>
              <p>
                Ilife is a booking company that provides a platform for users to
                book appointments with various businesses, such as restaurants,
                dental clinics, and more.
              </p>
            </li>
            <li className="mb-10">
              <h1 className="text-lg font-semibold mb-4">
                2. What types of businesses can I book through Ilife?
              </h1>
              <p>
                You can book appointments with various businesses, including
                restaurants, dental clinics, beauty salons, and more. The
                selection of businesses will vary depending on your location.
              </p>
            </li>
            <li className="mb-10">
              <h1 className="text-lg font-semibold mb-4">
                3. How do I book an appointment through Ilife?
              </h1>
              <p>
                To book an appointment through Ilife, simply go to the Ilife
                website, search for the business you wish to book with, select
                the date and time that works best for you, and follow the
                instructions to complete the booking process.
              </p>
            </li>
            <li className="mb-10">
              <h1 className="text-lg font-semibold mb-4">
                4. Can I make same-day bookings through Ilife?
              </h1>
              <p>
                Yes, Ilife provides the option to make same-day bookings,
                subject to availability.
              </p>
            </li>
            <li className="mb-10">
              <h1 className="text-lg font-semibold mb-4">
                5. What happens if I need to cancel or reschedule my
                appointment?
              </h1>
              <p>
                If you need to cancel or reschedule your appointment, you can do
                so through the Ilife platform. The cancellation policy for each
                business may vary, so it is important to review the details
                before confirming your booking.
              </p>
            </li>
            <li className="mb-10">
              <h1 className="text-lg font-semibold mb-4">
                6. Is there a fee for using Ilife
              </h1>
              <p>
                There may be a fee for using Ilife, depending on the business
                you are booking with. It is important to review the details and
                any applicable fees before confirming your booking.
              </p>
            </li>
          </ol>
        </div>
      </div>
    </div>
  );
}
