import Headermain from "../components/Headermain";
import Head from "next/head";
import { useSession, getSession } from "next-auth/react";
import { FaSearch } from "react-icons/fa";
import CardLayout from "../components/CardLayout/CardLayout";
import axios from "axios";
export default function Home({ userlist, productlist }) {
	const { data: session, status } = useSession();

	if (status === "authenticated") {
		return (
			<div className=" relative w-full h-full">
				<Head>
					<title>Ilife: Home</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon_io/favicon.ico" />
				</Head>

				<section className="bg-[url('/slider/mainbg.jpg')] bg-blend-overlay bg-cover bg-center bg-black bg-opacity-50">
					<Headermain userlist={userlist} />
					<section className="px-7 flex flex-col items-center">
						<h1 className="text-4xl text-white font-bold text-center mb-28 lg:text-6xl">
							Book everything. Yeah everything.
						</h1>
						<h3 className="text-xl lg:text-2xl lg:w-3/5  text-white text-center font-base mb-36">
							No more waiting in lines, loads of notebooks, confussion etc. It
							sounds like a dream came true, maybe because it did.
						</h3>
						<div className="flex justify-center mb-44 w-full">
							<div className="flex px-4 py-4 rounded-xl w-96 bg-white dark:bg-container-dark focus-within:last:outline focus-within:last:outline-4 focus-within:last:outline-icons focus-within:last:transition-all items-center gap-3">
								<FaSearch className="text-icons h-5 w-5" />
								<input
									className="text-md w-full bg-transparent outline-none focus:animate-none animate-pulse rounded-sm "
									type="search"
									placeholder="Search..."
								/>
							</div>
						</div>
					</section>
				</section>
				<main>
					<CardLayout productlist={productlist} />
				</main>
			</div>
		);
	}
}

export async function getServerSideProps({ req }) {
	const session = await getSession({ req });
	const res = await axios.get(`https://i-life.vercel.app/api/auth/signup`);
	const res2 = await axios.get(`https://i-life.vercel.app/api/products`);

	if (!session) {
		return {
			redirect: {
				destination: "/login",
				pernament: false,
			},
		};
	}

	return {
		props: { session, userlist: res.data, productlist: res2.data },
	};
}
