import Link from 'next/link';
import Image from 'next/image';
import Head from 'next/head';
import DarkSwitch from '../components/DarkSwitch';
export default function Policy() {
  return (
    <div>
      <Head>
        <title>Ilife: Privacy Policy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon_io/favicon.ico" />
      </Head>

      <nav className="flex justify-between px-4 py-6 md:px-10 lg:px-52 lg:py-6">
        <Link className="dark:hidden w-max" href="/">
          <Image src="/vibrant_logo.svg" width={130} height={130} />
        </Link>
        <Link className="dark:block" href="/">
          <Image src="/logo_white.svg" width={130} height={130} />
        </Link>
        <DarkSwitch />
      </nav>
      <div className="px-4 py-6 md:px-10 lg:px-52 lg:py-6">
        <h1 className="font-bold text-3xl mb-5">Privacy Policy</h1>
        <div className="w-5/6">
          <p>
            At Ilife, we take your privacy seriously. We understand that you
            trust us to handle your personal information, and we are committed
            to protecting it. This privacy policy (the &quot;Policy&quot;)
            explains how we collect, use, and share your personal information,
            as well as your rights in relation to your personal information.
            Collection of Personal Information We may collect personal
            information from you when you interact with us, such as when you
            visit our website, create an account, make a purchase, or contact
            customer support. The types of personal information we may collect
            include your name, email address, postal address, telephone number,
            and payment information. Use of Personal Information We use your
            personal information to provide and improve our products and
            services, to communicate with you, and to comply with legal
            obligations. For example, we may use your personal information to:
            process your orders and deliver the products you have purchased;
            send you promotional materials and updates on our products and
            services; respond to your customer service inquiries or requests;
            detect and prevent fraud or other illegal activities; comply with
            applicable laws and regulations. Sharing of Personal Information We
            may share your personal information with third parties in the
            following circumstances: with our service providers and partners,
            such as payment processors and shipping companies, to fulfill your
            orders and provide our services; with law enforcement or other
            government agencies, as required by law or to protect our rights and
            the rights of others; with other companies in the event of a merger
            or acquisition.
          </p>
          <br></br>
          <p>
            Your Rights You have certain rights in relation to your personal
            information, including: the right to access your personal
            information; the right to request the correction or deletion of your
            personal information; the right to object to the processing of your
            personal information; the right to request that we restrict the
            processing of your personal information; the right to receive your
            personal information in a portable format; the right to withdraw
            your consent to the processing of your personal information. We will
            respond to your requests in accordance with applicable laws. Changes
            to This Policy We may update this Policy from time to time to
            reflect changes to our practices or to comply with legal
            requirements. We will notify you of any material changes to this
            Policy by posting the new Policy on our website. Contact Us If you
            have any questions or concerns about this Policy or our handling of
            your personal information, please contact us at privacy@ilife.com
          </p>
        </div>
      </div>
    </div>
  );
}
