import Head from 'next/head';

export default function Seller() {
  <div>
    <Head>
      <title>Ilife: Become a seller</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon_io/favicon.ico" />
    </Head>
    <main></main>
  </div>;
}
