import Dashboard from "../../components/DashboardNavigation";
import { useSession, getSession } from "next-auth/react";
import Head from "next/head";
import ReservationsTable from "../../components/Reservations";
import axios from "axios";

export default function Reservations({ reservationslist }) {
	const { data: session, status } = useSession();

	if (status === "authenticated") {
		return (
			<div className="dark:bg-[url('/slider/dark_bg.jpg')] bg-[url('/slider/profile_back.jpg')] min-h-screen h-full bg-cover overflow-x-hidden lg:bg-gradient-to-br dark:lg:bg-gradient-to-br dark:lg:from-gray-600 lg:from-cyan-100 dark:lg:to-gray-900 dark:md:from-gray-600  dark:md:to-gray-900 lg:to-blue-300 md:bg-gradient-to-br dark:md:bg-gradient-to-br md:from-cyan-100 md:to-blue-300">
				<Head>
					<title>Ilife: Reservations</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon_io/favicon.ico" />
				</Head>

				<Dashboard />
				<main className="mx-2 mt-28 mb-4 lg:ml-44 lg:mr-2 lg:mx-0 lg:my-0 lg:mt-7">
					<ReservationsTable reservationslist={reservationslist} />
				</main>
			</div>
		);
	}
}

export async function getServerSideProps({ req }) {
	const session = await getSession({ req });
	const res = await axios.get(
		`https://i-life.vercel.app//api/reservations_u`,
	);

	if (!session) {
		return {
			redirect: {
				destination: "/",
				pernament: false,
			},
		};
	}

	return {
		props: { session, reservationslist: res.data },
	};
}
